### ISSUE TITLE
Strapi: Creation du blog

### ISSUE THREAD

**Issue by LouisLec** [GRINN-dev/next-strapi-tailwind-graphql-template#11]
# Blog

Le blog fait parti des features "minimales" à vendre dans le starter pack. Il doit etre possible pour les auteurs de rediger un article, de le publier ou non et d'associer un auteur à un article.

Pour ca, il va y avoir deux "collections" à créer dans strapi: une collection team members et une collection blog article.

## Collection Team Members
- [x] prenom
- [x] nom
- [x] mini-bio
- [x] avatar
- [x] liens RS (linkedin, twitter insta facebook tiktok et autre si tu y pense) pour ca dans strapi dans la creation de l'entité team members tu vas devoir ajouter un composant repetable, et dans ce composant tu mettra les differents type de RS qui existent plus un champ pour le lien

## Collection Blog Articles
- [x] Meta (il va falloir creer un composant, non-repetable ce coup ci) qu'on reutilisera dans d'autres collections qui va contenir les meta pour chaque page de notre blog
  - [x] page title
  - [x] page description
  - [x] keywords
  - [x] ttes les balises og et twitter
```html
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@nytimesbits" />
<meta name="twitter:creator" content="@nickbilton" />
<meta property="og:url" content="http://bits.blogs.nytimes.com/2011/12/08/a-twitter-for-my-sister/" />
<meta property="og:title" content="A Twitter for My Sister" />
<meta property="og:description" content="In the early days, Twitter grew so quickly that it was almost impossible to add new features because engineers spent their time trying to keep the rocket ship from stalling." />
<meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
```
- [x] titre de l'article
- [x] contenu (ca va etre du richtext)
- [x] auteur (relier à la collection team members)
- [x] date de publication
- [x] slug , cf: https://docs.strapi.io/developer-docs/latest/guides/slug.html

**Comment by NinonMaraval** [comment]
pour mémo pour créer les slugs (doc du site pas encore à jour) :
https://strapi.io/blog/how-to-create-a-slug-system-in-strapi-v4
